---
title: "Untitled"
author: "NatashaBertelsen"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Paths
```{r, warning=FALSE, message=FALSE}
library(easypackages)
libraries("tidyverse","ggheatmap","ggeasy","here","patchwork", "ggpubr")

codepath = here("code")
resultpath = here("results", "reval", "global")
plotdir = here("plots", "reval", "global")
plotdir_rsopen = file.path(plotdir, "rsopen")
plotdir_rsclosed = file.path(plotdir, "rsclosed")
```


```{r, warning = FALSE, message = FALSE}

rso = read.csv(file.path(resultpath,"14_rsopen_ALLrev_bootlim_data4plotting_LV1_ci95.csv"))

rso = rso[rso$VarName != "age",]
rso = rso[rso$VarName != "fiq",]

rso_td = rso %>% filter(Grp == "TD") %>% select(corr)
colnames(rso_td) = c("TD")
rso_a1 = rso %>% filter(Grp == "Autism 1") %>% select(corr)
colnames(rso_a1) = c("A1")
rso_a2 = rso %>% filter(Grp == "Autism 2") %>% select(corr)
colnames(rso_a2) = c("A2")

rso_tda1 = cbind(rso_td, rso_a1)
rso_tda2 = cbind(rso_td, rso_a2)

p_rso_tdva1 = ggplot(data = rso_tda1, aes(x = TD, y = A1)) + 
  geom_point() + geom_smooth(method = lm) + labs(title = 'rso td v a1') +
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, label.y.npc="bottom", label.x.npc = "centre", size = 3.5, colour = 'red') +
  xlim(-.05, .35) + ylim(-.2, .2)

p_rso_tdva2 = ggplot(data = rso_tda2, aes(x = TD, y = A2)) + 
  geom_point() + geom_smooth(method = lm) + labs(title = 'rso td v a2') +
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, label.y.npc="bottom", label.x.npc = "centre", size = 3.5, colour = 'red') +
  xlim(-.05, .35) + ylim(-.2, .2)


rsc = read.csv(file.path(resultpath, "14_rsclosed_ALL_bootlim_data4plotting_LV1_ci95.csv"))

rsc = rsc[rsc$VarName != "age",]
rsc = rsc[rsc$VarName != "fiq",]

rsc_td = rsc %>% filter(Grp == "TD") %>% select(corr)
colnames(rsc_td) = c("TD")
rsc_a1 = rsc %>% filter(Grp == "Autism 1") %>% select(corr)
colnames(rsc_a1) = c("A1")
rsc_a2 = rsc %>% filter(Grp == "Autism 2") %>% select(corr)
colnames(rsc_a2) = c("A2")

rsc_tda1 = cbind(rsc_td, rsc_a1)
rsc_tda2 = cbind(rsc_td, rsc_a2)

p_rsc_tdva1 = ggplot(data = rsc_tda1, aes(x = TD, y = A1)) + 
  geom_point() + geom_smooth(method = lm) + labs(title = 'rsc td v a1') +
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, label.y.npc="bottom", label.x.npc = "left", size = 3.5, colour = 'red') +
  xlim(-.05, .35) + ylim(-.2, .2)

p_rsc_tdva2 = ggplot(data = rsc_tda2, aes(x = TD, y = A2)) + 
  geom_point() + geom_smooth(method = lm) + labs(title = 'rsc td v a2') +
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, label.y.npc="bottom", label.x.npc = "left", size = 3.5, colour = 'red') +
  xlim(-.05, .35) + ylim(-.2, .2)

ggarrange(p_rso_tdva1, p_rso_tdva2, p_rsc_tdva1, p_rsc_tdva2, nrow = 2, ncol = 2)

```